// Automatically generated by PRGA's RTL generator
module cbox_clb_x0y0w (
    output wire [5:0] blkp_clb_x0y0_ia0,
    input wire [19:0] cbi_L1_u1y0n,
    input wire [19:0] cbi_L1_u1y0s,
    output wire [0:0] blkp_clb_x0y0_ib0,
    output wire [5:0] blkp_clb_x0y0_ia1,
    output wire [0:0] blkp_clb_x0y0_ib1,
    output wire [5:0] blkp_clb_x0y0_ia2,
    output wire [0:0] blkp_clb_x0y0_ib2,
    output wire [5:0] blkp_clb_x0y0_ia3,
    output wire [0:0] blkp_clb_x0y0_ib3,
    output wire [5:0] blkp_clb_x0y0_ia4,
    output wire [0:0] blkp_clb_x0y0_ib4,
    output wire [5:0] blkp_clb_x0y0_ia5,
    output wire [0:0] blkp_clb_x0y0_ib5,
    output wire [5:0] blkp_clb_x0y0_ia6,
    output wire [0:0] blkp_clb_x0y0_ib6,
    output wire [5:0] blkp_clb_x0y0_ia7,
    output wire [0:0] blkp_clb_x0y0_ib7,
    output wire [5:0] blkp_clb_x0y0_ia8,
    output wire [0:0] blkp_clb_x0y0_ib8,
    output wire [5:0] blkp_clb_x0y0_ia9,
    output wire [0:0] blkp_clb_x0y0_ib9,
    input wire [699:0] rows,
    input wire [699:0] cols
    );
    
    wire [0:0] sw_blkp_clb_x0y0_ia0_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib0_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib1_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib2_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib3_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib4_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib5_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib6_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib7_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib8_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib9_0__o;

    //distribute row/cols appropriately
    
    cfg_mux10 sw_blkp_clb_x0y0_ia0_0 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[0], cbi_L1_u1y0n[0]}),
        .o(sw_blkp_clb_x0y0_ia0_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_1 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia0_1__o),
        .rows(rows[19:10]),
        .cols(cols[19:10])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_2 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia0_2__o),
        .rows(rows[29:20]),
        .cols(cols[29:20])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_3 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia0_3__o),
        .rows(rows[39:30]),
        .cols(cols[39:30])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_4 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia0_4__o),
        .rows(rows[49:40]),
        .cols(cols[49:40])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_5 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia0_5__o),
        .rows(rows[59:50]),
        .cols(cols[59:50])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib0_0 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ib0_0__o),
        .rows(rows[69:60]),
        .cols(cols[69:60])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_0 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia1_0__o),
        .rows(rows[79:70]),
        .cols(cols[79:70])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_1 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia1_1__o),
        .rows(rows[89:80]),
        .cols(cols[89:80])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_2 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia1_2__o),
        .rows(rows[99:90]),
        .cols(cols[99:90])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_3 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia1_3__o),
        .rows(rows[109:100]),
        .cols(cols[109:100])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_4 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia1_4__o),
        .rows(rows[119:110]),
        .cols(cols[119:110])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_5 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia1_5__o),
        .rows(rows[129:120]),
        .cols(cols[129:120])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib1_0 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ib1_0__o),
        .rows(rows[139:130]),
        .cols(cols[139:130])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_0 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia2_0__o),
        .rows(rows[149:140]),
        .cols(cols[149:140])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_1 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia2_1__o),
        .rows(rows[159:150]),
        .cols(cols[159:150])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_2 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia2_2__o),
        .rows(rows[169:160]),
        .cols(cols[169:160])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_3 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia2_3__o),
        .rows(rows[179:170]),
        .cols(cols[179:170])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_4 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia2_4__o),
        .rows(rows[189:180]),
        .cols(cols[189:180])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_5 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia2_5__o),
        .rows(rows[199:190]),
        .cols(cols[199:190])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib2_0 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ib2_0__o),
        .rows(rows[209:200]),
        .cols(cols[209:200])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_0 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2]}),
        .o(sw_blkp_clb_x0y0_ia3_0__o),
        .rows(rows[219:210]),
        .cols(cols[219:210])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_1 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia3_1__o),
        .rows(rows[229:220]),
        .cols(cols[229:220])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_2 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia3_2__o),
        .rows(rows[239:230]),
        .cols(cols[239:230])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_3 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia3_3__o),
        .rows(rows[249:240]),
        .cols(cols[249:240])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_4 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia3_4__o),
        .rows(rows[259:250]),
        .cols(cols[259:250])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_5 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia3_5__o),
        .rows(rows[269:260]),
        .cols(cols[269:260])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib3_0 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ib3_0__o),
        .rows(rows[279:270]),
        .cols(cols[279:270])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_0 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9]}),
        .o(sw_blkp_clb_x0y0_ia4_0__o),
        .rows(rows[289:280]),
        .cols(cols[289:280])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_1 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ia4_1__o),
        .rows(rows[299:290]),
        .cols(cols[299:290])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_2 (
        .i({cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ia4_2__o),
        .rows(rows[309:300]),
        .cols(cols[309:300])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_3 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2]}),
        .o(sw_blkp_clb_x0y0_ia4_3__o),
        .rows(rows[319:310]),
        .cols(cols[319:310])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_4 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia4_4__o),
        .rows(rows[329:320]),
        .cols(cols[329:320])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_5 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia4_5__o),
        .rows(rows[339:330]),
        .cols(cols[339:330])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib4_0 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ib4_0__o),
        .rows(rows[349:340]),
        .cols(cols[349:340])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_0 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia5_0__o),
        .rows(rows[359:350]),
        .cols(cols[359:350])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_1 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia5_1__o),
        .rows(rows[369:360]),
        .cols(cols[369:360])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_2 (
        .i({cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ia5_2__o),
        .rows(rows[379:370]),
        .cols(cols[379:370])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_3 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9]}),
        .o(sw_blkp_clb_x0y0_ia5_3__o),
        .rows(rows[389:380]),
        .cols(cols[389:380])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_4 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ia5_4__o),
        .rows(rows[399:390]),
        .cols(cols[399:390])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_5 (
        .i({cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ia5_5__o),
        .rows(rows[409:400]),
        .cols(cols[409:400])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib5_0 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ib5_0__o),
        .rows(rows[419:410]),
        .cols(cols[419:410])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_0 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia6_0__o),
        .rows(rows[429:420]),
        .cols(cols[429:420])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_1 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia6_1__o),
        .rows(rows[439:430]),
        .cols(cols[439:430])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_2 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia6_2__o),
        .rows(rows[449:440]),
        .cols(cols[449:440])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_3 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia6_3__o),
        .rows(rows[459:450]),
        .cols(cols[459:450])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_4 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia6_4__o),
        .rows(rows[469:460]),
        .cols(cols[469:460])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_5 (
        .i({cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ia6_5__o),
        .rows(rows[479:470]),
        .cols(cols[479:470])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib6_0 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ib6_0__o),
        .rows(rows[489:480]),
        .cols(cols[489:480])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_0 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia7_0__o),
        .rows(rows[499:490]),
        .cols(cols[499:490])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_1 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia7_1__o),
        .rows(rows[509:500]),
        .cols(cols[509:500])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_2 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia7_2__o),
        .rows(rows[519:510]),
        .cols(cols[519:510])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_3 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia7_3__o),
        .rows(rows[529:520]),
        .cols(cols[529:520])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_4 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia7_4__o),
        .rows(rows[539:530]),
        .cols(cols[539:530])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_5 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia7_5__o),
        .rows(rows[549:540]),
        .cols(cols[549:540])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib7_0 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ib7_0__o),
        .rows(rows[559:550]),
        .cols(cols[559:550])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_0 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia8_0__o),
        .rows(rows[569:560]),
        .cols(cols[569:560])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_1 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia8_1__o),
        .rows(rows[579:570]),
        .cols(cols[579:570])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_2 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia8_2__o),
        .rows(rows[589:580]),
        .cols(cols[589:580])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_3 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia8_3__o),
        .rows(rows[599:590]),
        .cols(cols[599:590])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_4 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia8_4__o),
        .rows(rows[609:600]),
        .cols(cols[609:600])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_5 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia8_5__o),
        .rows(rows[619:610]),
        .cols(cols[619:610])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib8_0 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ib8_0__o),
        .rows(rows[629:620]),
        .cols(cols[629:620])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_0 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia9_0__o),
        .rows(rows[639:630]),
        .cols(cols[639:630])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_1 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia9_1__o),
        .rows(rows[649:640]),
        .cols(cols[649:640])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_2 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia9_2__o),
        .rows(rows[659:650]),
        .cols(cols[659:650])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_3 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia9_3__o),
        .rows(rows[669:660]),
        .cols(cols[669:660])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_4 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia9_4__o),
        .rows(rows[679:670]),
        .cols(cols[679:670])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_5 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia9_5__o),
        .rows(rows[689:680]),
        .cols(cols[689:680])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib9_0 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ib9_0__o),
        .rows(rows[699:690]),
        .cols(cols[699:690])

        );
    
    assign blkp_clb_x0y0_ia0 = {sw_blkp_clb_x0y0_ia0_5__o, sw_blkp_clb_x0y0_ia0_4__o, sw_blkp_clb_x0y0_ia0_3__o, sw_blkp_clb_x0y0_ia0_2__o, sw_blkp_clb_x0y0_ia0_1__o, sw_blkp_clb_x0y0_ia0_0__o};
    assign blkp_clb_x0y0_ib0 = sw_blkp_clb_x0y0_ib0_0__o;
    assign blkp_clb_x0y0_ia1 = {sw_blkp_clb_x0y0_ia1_5__o, sw_blkp_clb_x0y0_ia1_4__o, sw_blkp_clb_x0y0_ia1_3__o, sw_blkp_clb_x0y0_ia1_2__o, sw_blkp_clb_x0y0_ia1_1__o, sw_blkp_clb_x0y0_ia1_0__o};
    assign blkp_clb_x0y0_ib1 = sw_blkp_clb_x0y0_ib1_0__o;
    assign blkp_clb_x0y0_ia2 = {sw_blkp_clb_x0y0_ia2_5__o, sw_blkp_clb_x0y0_ia2_4__o, sw_blkp_clb_x0y0_ia2_3__o, sw_blkp_clb_x0y0_ia2_2__o, sw_blkp_clb_x0y0_ia2_1__o, sw_blkp_clb_x0y0_ia2_0__o};
    assign blkp_clb_x0y0_ib2 = sw_blkp_clb_x0y0_ib2_0__o;
    assign blkp_clb_x0y0_ia3 = {sw_blkp_clb_x0y0_ia3_5__o, sw_blkp_clb_x0y0_ia3_4__o, sw_blkp_clb_x0y0_ia3_3__o, sw_blkp_clb_x0y0_ia3_2__o, sw_blkp_clb_x0y0_ia3_1__o, sw_blkp_clb_x0y0_ia3_0__o};
    assign blkp_clb_x0y0_ib3 = sw_blkp_clb_x0y0_ib3_0__o;
    assign blkp_clb_x0y0_ia4 = {sw_blkp_clb_x0y0_ia4_5__o, sw_blkp_clb_x0y0_ia4_4__o, sw_blkp_clb_x0y0_ia4_3__o, sw_blkp_clb_x0y0_ia4_2__o, sw_blkp_clb_x0y0_ia4_1__o, sw_blkp_clb_x0y0_ia4_0__o};
    assign blkp_clb_x0y0_ib4 = sw_blkp_clb_x0y0_ib4_0__o;
    assign blkp_clb_x0y0_ia5 = {sw_blkp_clb_x0y0_ia5_5__o, sw_blkp_clb_x0y0_ia5_4__o, sw_blkp_clb_x0y0_ia5_3__o, sw_blkp_clb_x0y0_ia5_2__o, sw_blkp_clb_x0y0_ia5_1__o, sw_blkp_clb_x0y0_ia5_0__o};
    assign blkp_clb_x0y0_ib5 = sw_blkp_clb_x0y0_ib5_0__o;
    assign blkp_clb_x0y0_ia6 = {sw_blkp_clb_x0y0_ia6_5__o, sw_blkp_clb_x0y0_ia6_4__o, sw_blkp_clb_x0y0_ia6_3__o, sw_blkp_clb_x0y0_ia6_2__o, sw_blkp_clb_x0y0_ia6_1__o, sw_blkp_clb_x0y0_ia6_0__o};
    assign blkp_clb_x0y0_ib6 = sw_blkp_clb_x0y0_ib6_0__o;
    assign blkp_clb_x0y0_ia7 = {sw_blkp_clb_x0y0_ia7_5__o, sw_blkp_clb_x0y0_ia7_4__o, sw_blkp_clb_x0y0_ia7_3__o, sw_blkp_clb_x0y0_ia7_2__o, sw_blkp_clb_x0y0_ia7_1__o, sw_blkp_clb_x0y0_ia7_0__o};
    assign blkp_clb_x0y0_ib7 = sw_blkp_clb_x0y0_ib7_0__o;
    assign blkp_clb_x0y0_ia8 = {sw_blkp_clb_x0y0_ia8_5__o, sw_blkp_clb_x0y0_ia8_4__o, sw_blkp_clb_x0y0_ia8_3__o, sw_blkp_clb_x0y0_ia8_2__o, sw_blkp_clb_x0y0_ia8_1__o, sw_blkp_clb_x0y0_ia8_0__o};
    assign blkp_clb_x0y0_ib8 = sw_blkp_clb_x0y0_ib8_0__o;
    assign blkp_clb_x0y0_ia9 = {sw_blkp_clb_x0y0_ia9_5__o, sw_blkp_clb_x0y0_ia9_4__o, sw_blkp_clb_x0y0_ia9_3__o, sw_blkp_clb_x0y0_ia9_2__o, sw_blkp_clb_x0y0_ia9_1__o, sw_blkp_clb_x0y0_ia9_0__o};
    assign blkp_clb_x0y0_ib9 = sw_blkp_clb_x0y0_ib9_0__o;

endmodule
