// Automatically generated by PRGA's RTL generator
module cbox_clb_x0y0w (
    output wire [5:0] blkp_clb_x0y0_ia0,
    input wire [19:0] cbi_L1_u1y0n,
    input wire [19:0] cbi_L1_u1y0s,
    output wire [0:0] blkp_clb_x0y0_ib0,
    output wire [5:0] blkp_clb_x0y0_ia1,
    output wire [0:0] blkp_clb_x0y0_ib1,
    output wire [5:0] blkp_clb_x0y0_ia2,
    output wire [0:0] blkp_clb_x0y0_ib2,
    output wire [5:0] blkp_clb_x0y0_ia3,
    output wire [0:0] blkp_clb_x0y0_ib3,
    output wire [5:0] blkp_clb_x0y0_ia4,
    output wire [0:0] blkp_clb_x0y0_ib4,
    output wire [5:0] blkp_clb_x0y0_ia5,
    output wire [0:0] blkp_clb_x0y0_ib5,
    output wire [5:0] blkp_clb_x0y0_ia6,
    output wire [0:0] blkp_clb_x0y0_ib6,
    output wire [5:0] blkp_clb_x0y0_ia7,
    output wire [0:0] blkp_clb_x0y0_ib7,
    output wire [5:0] blkp_clb_x0y0_ia8,
    output wire [0:0] blkp_clb_x0y0_ib8,
    output wire [5:0] blkp_clb_x0y0_ia9,
    output wire [0:0] blkp_clb_x0y0_ib9,
    input wire [699:0] rows,
    input wire [699:0] cols,
    );
    
    wire [0:0] sw_blkp_clb_x0y0_ia0_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia0_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib0_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia1_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib1_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia2_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib2_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia3_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib3_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia4_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib4_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia5_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib5_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia6_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib6_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia7_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib7_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia8_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib8_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_0__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_1__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_2__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_3__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_4__o;
    wire [0:0] sw_blkp_clb_x0y0_ia9_5__o;
    wire [0:0] sw_blkp_clb_x0y0_ib9_0__o;

    //distribute row/cols appropriately
    
    cfg_mux10 sw_blkp_clb_x0y0_ia0_0 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[0], cbi_L1_u1y0n[0]}),
        .o(sw_blkp_clb_x0y0_ia0_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_1 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia0_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_2 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia0_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_3 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia0_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_4 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia0_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_ia0_5 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia0_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib0_0 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ib0_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_0 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia1_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_1 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia1_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_2 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia1_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_3 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia1_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_4 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia1_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia1_5 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia1_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib1_0 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ib1_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_0 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia2_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_1 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia2_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_2 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia2_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_3 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia2_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_4 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia2_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia2_5 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia2_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib2_0 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ib2_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_0 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2]}),
        .o(sw_blkp_clb_x0y0_ia3_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_1 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia3_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_2 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia3_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_3 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia3_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_4 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia3_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia3_5 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia3_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib3_0 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ib3_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_0 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9]}),
        .o(sw_blkp_clb_x0y0_ia4_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_1 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ia4_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_2 (
        .i({cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ia4_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_3 (
        .i({cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2]}),
        .o(sw_blkp_clb_x0y0_ia4_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_4 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia4_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia4_5 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia4_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib4_0 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ib4_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_0 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia5_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_1 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia5_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_2 (
        .i({cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ia5_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_3 (
        .i({cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9]}),
        .o(sw_blkp_clb_x0y0_ia5_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_4 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13]}),
        .o(sw_blkp_clb_x0y0_ia5_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia5_5 (
        .i({cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ia5_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib5_0 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ib5_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_0 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia6_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_1 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia6_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_2 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia6_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_3 (
        .i({cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16]}),
        .o(sw_blkp_clb_x0y0_ia6_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_4 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1]}),
        .o(sw_blkp_clb_x0y0_ia6_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia6_5 (
        .i({cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ia6_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib6_0 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ib6_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_0 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia7_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_1 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia7_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_2 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia7_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_3 (
        .i({cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4]}),
        .o(sw_blkp_clb_x0y0_ia7_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_4 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8]}),
        .o(sw_blkp_clb_x0y0_ia7_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia7_5 (
        .i({cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ia7_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib7_0 (
        .i({cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17]}),
        .o(sw_blkp_clb_x0y0_ib7_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_0 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia8_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_1 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia8_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_2 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia8_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_3 (
        .i({cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11]}),
        .o(sw_blkp_clb_x0y0_ia8_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_4 (
        .i({cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15]}),
        .o(sw_blkp_clb_x0y0_ia8_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia8_5 (
        .i({cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19]}),
        .o(sw_blkp_clb_x0y0_ia8_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib8_0 (
        .i({cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5]}),
        .o(sw_blkp_clb_x0y0_ib8_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_0 (
        .i({cbi_L1_u1y0s[7], cbi_L1_u1y0n[7], cbi_L1_u1y0s[2], cbi_L1_u1y0n[2], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6]}),
        .o(sw_blkp_clb_x0y0_ia9_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_1 (
        .i({cbi_L1_u1y0s[11], cbi_L1_u1y0n[11], cbi_L1_u1y0s[6], cbi_L1_u1y0n[6], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10]}),
        .o(sw_blkp_clb_x0y0_ia9_1__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_2 (
        .i({cbi_L1_u1y0s[15], cbi_L1_u1y0n[15], cbi_L1_u1y0s[10], cbi_L1_u1y0n[10], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14]}),
        .o(sw_blkp_clb_x0y0_ia9_2__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_3 (
        .i({cbi_L1_u1y0s[19], cbi_L1_u1y0n[19], cbi_L1_u1y0s[14], cbi_L1_u1y0n[14], cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18]}),
        .o(sw_blkp_clb_x0y0_ia9_3__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_4 (
        .i({cbi_L1_u1y0s[4], cbi_L1_u1y0n[4], cbi_L1_u1y0s[18], cbi_L1_u1y0n[18], cbi_L1_u1y0s[13], cbi_L1_u1y0n[13], cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3]}),
        .o(sw_blkp_clb_x0y0_ia9_4__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ia9_5 (
        .i({cbi_L1_u1y0s[8], cbi_L1_u1y0n[8], cbi_L1_u1y0s[3], cbi_L1_u1y0n[3], cbi_L1_u1y0s[17], cbi_L1_u1y0n[17], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12], cbi_L1_u1y0s[7], cbi_L1_u1y0n[7]}),
        .o(sw_blkp_clb_x0y0_ia9_5__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    cfg_mux10 sw_blkp_clb_x0y0_ib9_0 (
        .i({cbi_L1_u1y0s[9], cbi_L1_u1y0n[9], cbi_L1_u1y0s[5], cbi_L1_u1y0n[5], cbi_L1_u1y0s[1], cbi_L1_u1y0n[1], cbi_L1_u1y0s[16], cbi_L1_u1y0n[16], cbi_L1_u1y0s[12], cbi_L1_u1y0n[12]}),
        .o(sw_blkp_clb_x0y0_ib9_0__o),
        .rows(rows[9:0]),
        .cols(cols[9:0])

        );
    
    assign blkp_clb_x0y0_ia0 = {sw_blkp_clb_x0y0_ia0_5__o, sw_blkp_clb_x0y0_ia0_4__o, sw_blkp_clb_x0y0_ia0_3__o, sw_blkp_clb_x0y0_ia0_2__o, sw_blkp_clb_x0y0_ia0_1__o, sw_blkp_clb_x0y0_ia0_0__o};
    assign blkp_clb_x0y0_ib0 = sw_blkp_clb_x0y0_ib0_0__o;
    assign blkp_clb_x0y0_ia1 = {sw_blkp_clb_x0y0_ia1_5__o, sw_blkp_clb_x0y0_ia1_4__o, sw_blkp_clb_x0y0_ia1_3__o, sw_blkp_clb_x0y0_ia1_2__o, sw_blkp_clb_x0y0_ia1_1__o, sw_blkp_clb_x0y0_ia1_0__o};
    assign blkp_clb_x0y0_ib1 = sw_blkp_clb_x0y0_ib1_0__o;
    assign blkp_clb_x0y0_ia2 = {sw_blkp_clb_x0y0_ia2_5__o, sw_blkp_clb_x0y0_ia2_4__o, sw_blkp_clb_x0y0_ia2_3__o, sw_blkp_clb_x0y0_ia2_2__o, sw_blkp_clb_x0y0_ia2_1__o, sw_blkp_clb_x0y0_ia2_0__o};
    assign blkp_clb_x0y0_ib2 = sw_blkp_clb_x0y0_ib2_0__o;
    assign blkp_clb_x0y0_ia3 = {sw_blkp_clb_x0y0_ia3_5__o, sw_blkp_clb_x0y0_ia3_4__o, sw_blkp_clb_x0y0_ia3_3__o, sw_blkp_clb_x0y0_ia3_2__o, sw_blkp_clb_x0y0_ia3_1__o, sw_blkp_clb_x0y0_ia3_0__o};
    assign blkp_clb_x0y0_ib3 = sw_blkp_clb_x0y0_ib3_0__o;
    assign blkp_clb_x0y0_ia4 = {sw_blkp_clb_x0y0_ia4_5__o, sw_blkp_clb_x0y0_ia4_4__o, sw_blkp_clb_x0y0_ia4_3__o, sw_blkp_clb_x0y0_ia4_2__o, sw_blkp_clb_x0y0_ia4_1__o, sw_blkp_clb_x0y0_ia4_0__o};
    assign blkp_clb_x0y0_ib4 = sw_blkp_clb_x0y0_ib4_0__o;
    assign blkp_clb_x0y0_ia5 = {sw_blkp_clb_x0y0_ia5_5__o, sw_blkp_clb_x0y0_ia5_4__o, sw_blkp_clb_x0y0_ia5_3__o, sw_blkp_clb_x0y0_ia5_2__o, sw_blkp_clb_x0y0_ia5_1__o, sw_blkp_clb_x0y0_ia5_0__o};
    assign blkp_clb_x0y0_ib5 = sw_blkp_clb_x0y0_ib5_0__o;
    assign blkp_clb_x0y0_ia6 = {sw_blkp_clb_x0y0_ia6_5__o, sw_blkp_clb_x0y0_ia6_4__o, sw_blkp_clb_x0y0_ia6_3__o, sw_blkp_clb_x0y0_ia6_2__o, sw_blkp_clb_x0y0_ia6_1__o, sw_blkp_clb_x0y0_ia6_0__o};
    assign blkp_clb_x0y0_ib6 = sw_blkp_clb_x0y0_ib6_0__o;
    assign blkp_clb_x0y0_ia7 = {sw_blkp_clb_x0y0_ia7_5__o, sw_blkp_clb_x0y0_ia7_4__o, sw_blkp_clb_x0y0_ia7_3__o, sw_blkp_clb_x0y0_ia7_2__o, sw_blkp_clb_x0y0_ia7_1__o, sw_blkp_clb_x0y0_ia7_0__o};
    assign blkp_clb_x0y0_ib7 = sw_blkp_clb_x0y0_ib7_0__o;
    assign blkp_clb_x0y0_ia8 = {sw_blkp_clb_x0y0_ia8_5__o, sw_blkp_clb_x0y0_ia8_4__o, sw_blkp_clb_x0y0_ia8_3__o, sw_blkp_clb_x0y0_ia8_2__o, sw_blkp_clb_x0y0_ia8_1__o, sw_blkp_clb_x0y0_ia8_0__o};
    assign blkp_clb_x0y0_ib8 = sw_blkp_clb_x0y0_ib8_0__o;
    assign blkp_clb_x0y0_ia9 = {sw_blkp_clb_x0y0_ia9_5__o, sw_blkp_clb_x0y0_ia9_4__o, sw_blkp_clb_x0y0_ia9_3__o, sw_blkp_clb_x0y0_ia9_2__o, sw_blkp_clb_x0y0_ia9_1__o, sw_blkp_clb_x0y0_ia9_0__o};
    assign blkp_clb_x0y0_ib9 = sw_blkp_clb_x0y0_ib9_0__o;

endmodule
