#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli -t tools.yml -c config/fpga.yml -c config/cds.yml -c config/jobs.yml --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "fpga" 
#----------------------------------------------------------
fpga: 
	toolbox-cli -t tools.yml -c config/fpga.yml -c config/cds.yml -c config/jobs.yml --color -l info -b build -o toolbox fpga	
.PHONY: fpga
#----------------------------------------------------------

#----------------------------------------------------------
# Target "lef" 
#----------------------------------------------------------
lef: 
	toolbox-cli -t tools.yml -c config/fpga.yml -c config/cds.yml -c config/jobs.yml --color -l info -b build -o toolbox lef	
.PHONY: lef
#----------------------------------------------------------

#----------------------------------------------------------
# Target "lib" 
#----------------------------------------------------------
lib: 
	toolbox-cli -t tools.yml -c config/fpga.yml -c config/cds.yml -c config/jobs.yml --color -l info -b build -o toolbox lib	
.PHONY: lib
#----------------------------------------------------------

#----------------------------------------------------------
# Target "reports" 
#----------------------------------------------------------
reports: 
	toolbox-cli -t tools.yml -c config/fpga.yml -c config/cds.yml -c config/jobs.yml --color -l info -b build -o toolbox reports	
.PHONY: reports
#----------------------------------------------------------

#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build      Builds a makefile for running toolbox jobs"
	@echo "fpga       Builds a very simple FPGA for evaluation purposes"
	@echo "lef        Generates a .lef for the NEMs device"
	@echo "lib        Generates a .lib for the NEMs device"
	@echo "reports    Plots design report information"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------
