#----------------------------------------------------------
# Target "build" 
#----------------------------------------------------------
build: 
	toolbox-cli -t tools.yml -c config/jobs.yml -c config/fpga.yml --color -l info -b build -o toolbox build	
.PHONY: build
#----------------------------------------------------------

#----------------------------------------------------------
# Target "fpga" 
#----------------------------------------------------------
fpga: 
	toolbox-cli -t tools.yml -c config/jobs.yml -c config/fpga.yml --color -l info -b build -o toolbox fpga	
.PHONY: fpga
#----------------------------------------------------------

#----------------------------------------------------------
# Target "list" - lists all found jobs
#----------------------------------------------------------
list:
	@echo "#--------------------------------------------------------------------"
	@echo "# Toolbox generated make targets"
	@echo "#--------------------------------------------------------------------"
	@echo "build    Builds a makefile for running toolbox jobs"
	@echo "fpga     Builds a very simple FPGA for evaluation purposes"
	@echo "#--------------------------------------------------------------------"
.PHONY: list 
#----------------------------------------------------------