// Automatically generated by PRGA's RTL generator
module cbox_clb_x0y0e (
    input wire [0:0] blkp_clb_x0y0_oa0,
    output wire [19:0] cbo_L4_x0y0n,
    output wire [19:0] cbo_L4_x0y0s,
    input wire [0:0] blkp_clb_x0y0_ob0,
    input wire [0:0] blkp_clb_x0y0_q0,
    input wire [0:0] blkp_clb_x0y0_oa1,
    input wire [0:0] blkp_clb_x0y0_ob1,
    input wire [0:0] blkp_clb_x0y0_q1,
    input wire [0:0] blkp_clb_x0y0_oa2,
    input wire [0:0] blkp_clb_x0y0_ob2,
    input wire [0:0] blkp_clb_x0y0_q2,
    input wire [0:0] blkp_clb_x0y0_oa3,
    input wire [0:0] blkp_clb_x0y0_ob3,
    input wire [0:0] blkp_clb_x0y0_q3,
    input wire [0:0] blkp_clb_x0y0_oa4,
    input wire [0:0] blkp_clb_x0y0_ob4,
    input wire [0:0] blkp_clb_x0y0_q4,
    input wire [0:0] blkp_clb_x0y0_oa5,
    input wire [0:0] blkp_clb_x0y0_ob5,
    input wire [0:0] blkp_clb_x0y0_q5,
    input wire [0:0] blkp_clb_x0y0_oa6,
    input wire [0:0] blkp_clb_x0y0_ob6,
    input wire [0:0] blkp_clb_x0y0_q6,
    input wire [0:0] blkp_clb_x0y0_oa7,
    input wire [0:0] blkp_clb_x0y0_ob7,
    input wire [0:0] blkp_clb_x0y0_q7,
    input wire [0:0] blkp_clb_x0y0_oa8,
    input wire [0:0] blkp_clb_x0y0_ob8,
    input wire [0:0] blkp_clb_x0y0_q8,
    input wire [0:0] blkp_clb_x0y0_oa9,
    input wire [0:0] blkp_clb_x0y0_ob9,
    input wire [0:0] blkp_clb_x0y0_q9,
    input wire [75:0] cfg_d
    );
    
    wire [0:0] sw_cbo_L4_x0y0n_1__o;
    wire [0:0] sw_cbo_L4_x0y0n_2__o;
    wire [0:0] sw_cbo_L4_x0y0n_3__o;
    wire [0:0] sw_cbo_L4_x0y0n_4__o;
    wire [0:0] sw_cbo_L4_x0y0n_5__o;
    wire [0:0] sw_cbo_L4_x0y0n_6__o;
    wire [0:0] sw_cbo_L4_x0y0n_7__o;
    wire [0:0] sw_cbo_L4_x0y0n_8__o;
    wire [0:0] sw_cbo_L4_x0y0n_9__o;
    wire [0:0] sw_cbo_L4_x0y0n_10__o;
    wire [0:0] sw_cbo_L4_x0y0n_11__o;
    wire [0:0] sw_cbo_L4_x0y0n_12__o;
    wire [0:0] sw_cbo_L4_x0y0n_13__o;
    wire [0:0] sw_cbo_L4_x0y0n_14__o;
    wire [0:0] sw_cbo_L4_x0y0n_15__o;
    wire [0:0] sw_cbo_L4_x0y0n_16__o;
    wire [0:0] sw_cbo_L4_x0y0n_17__o;
    wire [0:0] sw_cbo_L4_x0y0n_18__o;
    wire [0:0] sw_cbo_L4_x0y0n_19__o;
    wire [0:0] sw_cbo_L4_x0y0s_1__o;
    wire [0:0] sw_cbo_L4_x0y0s_2__o;
    wire [0:0] sw_cbo_L4_x0y0s_3__o;
    wire [0:0] sw_cbo_L4_x0y0s_4__o;
    wire [0:0] sw_cbo_L4_x0y0s_5__o;
    wire [0:0] sw_cbo_L4_x0y0s_6__o;
    wire [0:0] sw_cbo_L4_x0y0s_7__o;
    wire [0:0] sw_cbo_L4_x0y0s_8__o;
    wire [0:0] sw_cbo_L4_x0y0s_9__o;
    wire [0:0] sw_cbo_L4_x0y0s_10__o;
    wire [0:0] sw_cbo_L4_x0y0s_11__o;
    wire [0:0] sw_cbo_L4_x0y0s_12__o;
    wire [0:0] sw_cbo_L4_x0y0s_13__o;
    wire [0:0] sw_cbo_L4_x0y0s_14__o;
    wire [0:0] sw_cbo_L4_x0y0s_15__o;
    wire [0:0] sw_cbo_L4_x0y0s_16__o;
    wire [0:0] sw_cbo_L4_x0y0s_17__o;
    wire [0:0] sw_cbo_L4_x0y0s_18__o;
    wire [0:0] sw_cbo_L4_x0y0s_19__o;
    
    cfg_mux4 sw_cbo_L4_x0y0n_1 (
        .i({blkp_clb_x0y0_q9, blkp_clb_x0y0_q6, blkp_clb_x0y0_ob3, blkp_clb_x0y0_ob0}),
        .o(sw_cbo_L4_x0y0n_1__o),
        .cfg_d(cfg_d[1:0])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_2 (
        .i({blkp_clb_x0y0_oa7, blkp_clb_x0y0_q3, blkp_clb_x0y0_q0}),
        .o(sw_cbo_L4_x0y0n_2__o),
        .cfg_d(cfg_d[3:2])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_3 (
        .i({blkp_clb_x0y0_ob7, blkp_clb_x0y0_oa4, blkp_clb_x0y0_oa1}),
        .o(sw_cbo_L4_x0y0n_3__o),
        .cfg_d(cfg_d[5:4])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_4 (
        .i({blkp_clb_x0y0_q7, blkp_clb_x0y0_ob4, blkp_clb_x0y0_ob1}),
        .o(sw_cbo_L4_x0y0n_4__o),
        .cfg_d(cfg_d[7:6])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_5 (
        .i({blkp_clb_x0y0_oa8, blkp_clb_x0y0_q4, blkp_clb_x0y0_q1}),
        .o(sw_cbo_L4_x0y0n_5__o),
        .cfg_d(cfg_d[9:8])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_6 (
        .i({blkp_clb_x0y0_ob8, blkp_clb_x0y0_oa5, blkp_clb_x0y0_oa2}),
        .o(sw_cbo_L4_x0y0n_6__o),
        .cfg_d(cfg_d[11:10])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_7 (
        .i({blkp_clb_x0y0_q8, blkp_clb_x0y0_ob5, blkp_clb_x0y0_ob2}),
        .o(sw_cbo_L4_x0y0n_7__o),
        .cfg_d(cfg_d[13:12])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_8 (
        .i({blkp_clb_x0y0_oa9, blkp_clb_x0y0_q5, blkp_clb_x0y0_q2}),
        .o(sw_cbo_L4_x0y0n_8__o),
        .cfg_d(cfg_d[15:14])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_9 (
        .i({blkp_clb_x0y0_ob9, blkp_clb_x0y0_oa6, blkp_clb_x0y0_oa3}),
        .o(sw_cbo_L4_x0y0n_9__o),
        .cfg_d(cfg_d[17:16])
        );
    cfg_mux4 sw_cbo_L4_x0y0n_10 (
        .i({blkp_clb_x0y0_q9, blkp_clb_x0y0_ob6, blkp_clb_x0y0_ob3, blkp_clb_x0y0_oa0}),
        .o(sw_cbo_L4_x0y0n_10__o),
        .cfg_d(cfg_d[19:18])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_11 (
        .i({blkp_clb_x0y0_q6, blkp_clb_x0y0_q3, blkp_clb_x0y0_ob0}),
        .o(sw_cbo_L4_x0y0n_11__o),
        .cfg_d(cfg_d[21:20])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_12 (
        .i({blkp_clb_x0y0_oa7, blkp_clb_x0y0_oa4, blkp_clb_x0y0_q0}),
        .o(sw_cbo_L4_x0y0n_12__o),
        .cfg_d(cfg_d[23:22])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_13 (
        .i({blkp_clb_x0y0_ob7, blkp_clb_x0y0_ob4, blkp_clb_x0y0_oa1}),
        .o(sw_cbo_L4_x0y0n_13__o),
        .cfg_d(cfg_d[25:24])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_14 (
        .i({blkp_clb_x0y0_q7, blkp_clb_x0y0_q4, blkp_clb_x0y0_ob1}),
        .o(sw_cbo_L4_x0y0n_14__o),
        .cfg_d(cfg_d[27:26])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_15 (
        .i({blkp_clb_x0y0_oa8, blkp_clb_x0y0_oa5, blkp_clb_x0y0_q1}),
        .o(sw_cbo_L4_x0y0n_15__o),
        .cfg_d(cfg_d[29:28])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_16 (
        .i({blkp_clb_x0y0_ob8, blkp_clb_x0y0_ob5, blkp_clb_x0y0_oa2}),
        .o(sw_cbo_L4_x0y0n_16__o),
        .cfg_d(cfg_d[31:30])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_17 (
        .i({blkp_clb_x0y0_q8, blkp_clb_x0y0_q5, blkp_clb_x0y0_ob2}),
        .o(sw_cbo_L4_x0y0n_17__o),
        .cfg_d(cfg_d[33:32])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_18 (
        .i({blkp_clb_x0y0_oa9, blkp_clb_x0y0_oa6, blkp_clb_x0y0_q2}),
        .o(sw_cbo_L4_x0y0n_18__o),
        .cfg_d(cfg_d[35:34])
        );
    cfg_mux3 sw_cbo_L4_x0y0n_19 (
        .i({blkp_clb_x0y0_ob9, blkp_clb_x0y0_ob6, blkp_clb_x0y0_oa3}),
        .o(sw_cbo_L4_x0y0n_19__o),
        .cfg_d(cfg_d[37:36])
        );
    cfg_mux4 sw_cbo_L4_x0y0s_1 (
        .i({blkp_clb_x0y0_q9, blkp_clb_x0y0_q6, blkp_clb_x0y0_ob3, blkp_clb_x0y0_ob0}),
        .o(sw_cbo_L4_x0y0s_1__o),
        .cfg_d(cfg_d[39:38])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_2 (
        .i({blkp_clb_x0y0_oa7, blkp_clb_x0y0_q3, blkp_clb_x0y0_q0}),
        .o(sw_cbo_L4_x0y0s_2__o),
        .cfg_d(cfg_d[41:40])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_3 (
        .i({blkp_clb_x0y0_ob7, blkp_clb_x0y0_oa4, blkp_clb_x0y0_oa1}),
        .o(sw_cbo_L4_x0y0s_3__o),
        .cfg_d(cfg_d[43:42])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_4 (
        .i({blkp_clb_x0y0_q7, blkp_clb_x0y0_ob4, blkp_clb_x0y0_ob1}),
        .o(sw_cbo_L4_x0y0s_4__o),
        .cfg_d(cfg_d[45:44])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_5 (
        .i({blkp_clb_x0y0_oa8, blkp_clb_x0y0_q4, blkp_clb_x0y0_q1}),
        .o(sw_cbo_L4_x0y0s_5__o),
        .cfg_d(cfg_d[47:46])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_6 (
        .i({blkp_clb_x0y0_ob8, blkp_clb_x0y0_oa5, blkp_clb_x0y0_oa2}),
        .o(sw_cbo_L4_x0y0s_6__o),
        .cfg_d(cfg_d[49:48])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_7 (
        .i({blkp_clb_x0y0_q8, blkp_clb_x0y0_ob5, blkp_clb_x0y0_ob2}),
        .o(sw_cbo_L4_x0y0s_7__o),
        .cfg_d(cfg_d[51:50])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_8 (
        .i({blkp_clb_x0y0_oa9, blkp_clb_x0y0_q5, blkp_clb_x0y0_q2}),
        .o(sw_cbo_L4_x0y0s_8__o),
        .cfg_d(cfg_d[53:52])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_9 (
        .i({blkp_clb_x0y0_ob9, blkp_clb_x0y0_oa6, blkp_clb_x0y0_oa3}),
        .o(sw_cbo_L4_x0y0s_9__o),
        .cfg_d(cfg_d[55:54])
        );
    cfg_mux4 sw_cbo_L4_x0y0s_10 (
        .i({blkp_clb_x0y0_q9, blkp_clb_x0y0_ob6, blkp_clb_x0y0_ob3, blkp_clb_x0y0_oa0}),
        .o(sw_cbo_L4_x0y0s_10__o),
        .cfg_d(cfg_d[57:56])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_11 (
        .i({blkp_clb_x0y0_q6, blkp_clb_x0y0_q3, blkp_clb_x0y0_ob0}),
        .o(sw_cbo_L4_x0y0s_11__o),
        .cfg_d(cfg_d[59:58])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_12 (
        .i({blkp_clb_x0y0_oa7, blkp_clb_x0y0_oa4, blkp_clb_x0y0_q0}),
        .o(sw_cbo_L4_x0y0s_12__o),
        .cfg_d(cfg_d[61:60])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_13 (
        .i({blkp_clb_x0y0_ob7, blkp_clb_x0y0_ob4, blkp_clb_x0y0_oa1}),
        .o(sw_cbo_L4_x0y0s_13__o),
        .cfg_d(cfg_d[63:62])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_14 (
        .i({blkp_clb_x0y0_q7, blkp_clb_x0y0_q4, blkp_clb_x0y0_ob1}),
        .o(sw_cbo_L4_x0y0s_14__o),
        .cfg_d(cfg_d[65:64])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_15 (
        .i({blkp_clb_x0y0_oa8, blkp_clb_x0y0_oa5, blkp_clb_x0y0_q1}),
        .o(sw_cbo_L4_x0y0s_15__o),
        .cfg_d(cfg_d[67:66])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_16 (
        .i({blkp_clb_x0y0_ob8, blkp_clb_x0y0_ob5, blkp_clb_x0y0_oa2}),
        .o(sw_cbo_L4_x0y0s_16__o),
        .cfg_d(cfg_d[69:68])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_17 (
        .i({blkp_clb_x0y0_q8, blkp_clb_x0y0_q5, blkp_clb_x0y0_ob2}),
        .o(sw_cbo_L4_x0y0s_17__o),
        .cfg_d(cfg_d[71:70])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_18 (
        .i({blkp_clb_x0y0_oa9, blkp_clb_x0y0_oa6, blkp_clb_x0y0_q2}),
        .o(sw_cbo_L4_x0y0s_18__o),
        .cfg_d(cfg_d[73:72])
        );
    cfg_mux3 sw_cbo_L4_x0y0s_19 (
        .i({blkp_clb_x0y0_ob9, blkp_clb_x0y0_ob6, blkp_clb_x0y0_oa3}),
        .o(sw_cbo_L4_x0y0s_19__o),
        .cfg_d(cfg_d[75:74])
        );
    
    assign cbo_L4_x0y0n = {sw_cbo_L4_x0y0n_19__o, sw_cbo_L4_x0y0n_18__o, sw_cbo_L4_x0y0n_17__o, sw_cbo_L4_x0y0n_16__o, sw_cbo_L4_x0y0n_15__o, sw_cbo_L4_x0y0n_14__o, sw_cbo_L4_x0y0n_13__o, sw_cbo_L4_x0y0n_12__o, sw_cbo_L4_x0y0n_11__o, sw_cbo_L4_x0y0n_10__o, sw_cbo_L4_x0y0n_9__o, sw_cbo_L4_x0y0n_8__o, sw_cbo_L4_x0y0n_7__o, sw_cbo_L4_x0y0n_6__o, sw_cbo_L4_x0y0n_5__o, sw_cbo_L4_x0y0n_4__o, sw_cbo_L4_x0y0n_3__o, sw_cbo_L4_x0y0n_2__o, sw_cbo_L4_x0y0n_1__o, blkp_clb_x0y0_oa0};
    assign cbo_L4_x0y0s = {sw_cbo_L4_x0y0s_19__o, sw_cbo_L4_x0y0s_18__o, sw_cbo_L4_x0y0s_17__o, sw_cbo_L4_x0y0s_16__o, sw_cbo_L4_x0y0s_15__o, sw_cbo_L4_x0y0s_14__o, sw_cbo_L4_x0y0s_13__o, sw_cbo_L4_x0y0s_12__o, sw_cbo_L4_x0y0s_11__o, sw_cbo_L4_x0y0s_10__o, sw_cbo_L4_x0y0s_9__o, sw_cbo_L4_x0y0s_8__o, sw_cbo_L4_x0y0s_7__o, sw_cbo_L4_x0y0s_6__o, sw_cbo_L4_x0y0s_5__o, sw_cbo_L4_x0y0s_4__o, sw_cbo_L4_x0y0s_3__o, sw_cbo_L4_x0y0s_2__o, sw_cbo_L4_x0y0s_1__o, blkp_clb_x0y0_oa0};

endmodule
