// Automatically generated by PRGA's RTL generator
module clb (
    input wire [0:0] clk,
    input wire [0:0] ce,
    input wire [0:0] sr,
    input wire [0:0] cin,
    output wire [0:0] cout,
    input wire [5:0] ia0,
    input wire [0:0] ib0,
    output wire [0:0] oa0,
    output wire [0:0] ob0,
    output wire [0:0] q0,
    input wire [5:0] ia1,
    input wire [0:0] ib1,
    output wire [0:0] oa1,
    output wire [0:0] ob1,
    output wire [0:0] q1,
    input wire [5:0] ia2,
    input wire [0:0] ib2,
    output wire [0:0] oa2,
    output wire [0:0] ob2,
    output wire [0:0] q2,
    input wire [5:0] ia3,
    input wire [0:0] ib3,
    output wire [0:0] oa3,
    output wire [0:0] ob3,
    output wire [0:0] q3,
    input wire [5:0] ia4,
    input wire [0:0] ib4,
    output wire [0:0] oa4,
    output wire [0:0] ob4,
    output wire [0:0] q4,
    input wire [5:0] ia5,
    input wire [0:0] ib5,
    output wire [0:0] oa5,
    output wire [0:0] ob5,
    output wire [0:0] q5,
    input wire [5:0] ia6,
    input wire [0:0] ib6,
    output wire [0:0] oa6,
    output wire [0:0] ob6,
    output wire [0:0] q6,
    input wire [5:0] ia7,
    input wire [0:0] ib7,
    output wire [0:0] oa7,
    output wire [0:0] ob7,
    output wire [0:0] q7,
    input wire [5:0] ia8,
    input wire [0:0] ib8,
    output wire [0:0] oa8,
    output wire [0:0] ob8,
    output wire [0:0] q8,
    input wire [5:0] ia9,
    input wire [0:0] ib9,
    output wire [0:0] oa9,
    output wire [0:0] ob9,
    output wire [0:0] q9,
    input wire [0:0] cfg_clk,
    input wire [0:0] cfg_e,
    input wire [0:0] cfg_we,
    input wire [0:0] cfg_i,
    output wire [0:0] cfg_o
    );
    
    wire [0:0] cluster0__cout;
    wire [0:0] cluster0__oa;
    wire [0:0] cluster0__ob;
    wire [0:0] cluster0__q;
    wire [0:0] cluster0__cfg_o;
    wire [0:0] cluster1__cout;
    wire [0:0] cluster1__oa;
    wire [0:0] cluster1__ob;
    wire [0:0] cluster1__q;
    wire [0:0] cluster1__cfg_o;
    wire [0:0] cluster2__cout;
    wire [0:0] cluster2__oa;
    wire [0:0] cluster2__ob;
    wire [0:0] cluster2__q;
    wire [0:0] cluster2__cfg_o;
    wire [0:0] cluster3__cout;
    wire [0:0] cluster3__oa;
    wire [0:0] cluster3__ob;
    wire [0:0] cluster3__q;
    wire [0:0] cluster3__cfg_o;
    wire [0:0] cluster4__cout;
    wire [0:0] cluster4__oa;
    wire [0:0] cluster4__ob;
    wire [0:0] cluster4__q;
    wire [0:0] cluster4__cfg_o;
    wire [0:0] cluster5__cout;
    wire [0:0] cluster5__oa;
    wire [0:0] cluster5__ob;
    wire [0:0] cluster5__q;
    wire [0:0] cluster5__cfg_o;
    wire [0:0] cluster6__cout;
    wire [0:0] cluster6__oa;
    wire [0:0] cluster6__ob;
    wire [0:0] cluster6__q;
    wire [0:0] cluster6__cfg_o;
    wire [0:0] cluster7__cout;
    wire [0:0] cluster7__oa;
    wire [0:0] cluster7__ob;
    wire [0:0] cluster7__q;
    wire [0:0] cluster7__cfg_o;
    wire [0:0] cluster8__cout;
    wire [0:0] cluster8__oa;
    wire [0:0] cluster8__ob;
    wire [0:0] cluster8__q;
    wire [0:0] cluster8__cfg_o;
    wire [0:0] cluster9__cout;
    wire [0:0] cluster9__oa;
    wire [0:0] cluster9__ob;
    wire [0:0] cluster9__q;
    wire [0:0] cluster9__cfg_o;
    
    fraclut6sffc cluster0 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia0),
        .ib(ib0),
        .cin(cin),
        .cout(cluster0__cout),
        .oa(cluster0__oa),
        .ob(cluster0__ob),
        .q(cluster0__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cfg_i),
        .cfg_o(cluster0__cfg_o)
        );
    fraclut6sffc cluster1 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia1),
        .ib(ib1),
        .cin(cluster0__cout),
        .cout(cluster1__cout),
        .oa(cluster1__oa),
        .ob(cluster1__ob),
        .q(cluster1__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster0__cfg_o),
        .cfg_o(cluster1__cfg_o)
        );
    fraclut6sffc cluster2 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia2),
        .ib(ib2),
        .cin(cluster1__cout),
        .cout(cluster2__cout),
        .oa(cluster2__oa),
        .ob(cluster2__ob),
        .q(cluster2__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster1__cfg_o),
        .cfg_o(cluster2__cfg_o)
        );
    fraclut6sffc cluster3 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia3),
        .ib(ib3),
        .cin(cluster2__cout),
        .cout(cluster3__cout),
        .oa(cluster3__oa),
        .ob(cluster3__ob),
        .q(cluster3__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster2__cfg_o),
        .cfg_o(cluster3__cfg_o)
        );
    fraclut6sffc cluster4 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia4),
        .ib(ib4),
        .cin(cluster3__cout),
        .cout(cluster4__cout),
        .oa(cluster4__oa),
        .ob(cluster4__ob),
        .q(cluster4__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster3__cfg_o),
        .cfg_o(cluster4__cfg_o)
        );
    fraclut6sffc cluster5 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia5),
        .ib(ib5),
        .cin(cluster4__cout),
        .cout(cluster5__cout),
        .oa(cluster5__oa),
        .ob(cluster5__ob),
        .q(cluster5__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster4__cfg_o),
        .cfg_o(cluster5__cfg_o)
        );
    fraclut6sffc cluster6 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia6),
        .ib(ib6),
        .cin(cluster5__cout),
        .cout(cluster6__cout),
        .oa(cluster6__oa),
        .ob(cluster6__ob),
        .q(cluster6__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster5__cfg_o),
        .cfg_o(cluster6__cfg_o)
        );
    fraclut6sffc cluster7 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia7),
        .ib(ib7),
        .cin(cluster6__cout),
        .cout(cluster7__cout),
        .oa(cluster7__oa),
        .ob(cluster7__ob),
        .q(cluster7__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster6__cfg_o),
        .cfg_o(cluster7__cfg_o)
        );
    fraclut6sffc cluster8 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia8),
        .ib(ib8),
        .cin(cluster7__cout),
        .cout(cluster8__cout),
        .oa(cluster8__oa),
        .ob(cluster8__ob),
        .q(cluster8__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster7__cfg_o),
        .cfg_o(cluster8__cfg_o)
        );
    fraclut6sffc cluster9 (
        .clk(clk),
        .ce(ce),
        .sr(sr),
        .ia(ia9),
        .ib(ib9),
        .cin(cluster8__cout),
        .cout(cluster9__cout),
        .oa(cluster9__oa),
        .ob(cluster9__ob),
        .q(cluster9__q),
        .cfg_clk(cfg_clk),
        .cfg_e(cfg_e),
        .cfg_we(cfg_we),
        .cfg_i(cluster8__cfg_o),
        .cfg_o(cluster9__cfg_o)
        );
    
    assign cout = cluster9__cout;
    assign oa0 = cluster0__oa;
    assign ob0 = cluster0__ob;
    assign q0 = cluster0__q;
    assign oa1 = cluster1__oa;
    assign ob1 = cluster1__ob;
    assign q1 = cluster1__q;
    assign oa2 = cluster2__oa;
    assign ob2 = cluster2__ob;
    assign q2 = cluster2__q;
    assign oa3 = cluster3__oa;
    assign ob3 = cluster3__ob;
    assign q3 = cluster3__q;
    assign oa4 = cluster4__oa;
    assign ob4 = cluster4__ob;
    assign q4 = cluster4__q;
    assign oa5 = cluster5__oa;
    assign ob5 = cluster5__ob;
    assign q5 = cluster5__q;
    assign oa6 = cluster6__oa;
    assign ob6 = cluster6__ob;
    assign q6 = cluster6__q;
    assign oa7 = cluster7__oa;
    assign ob7 = cluster7__ob;
    assign q7 = cluster7__q;
    assign oa8 = cluster8__oa;
    assign ob8 = cluster8__ob;
    assign q8 = cluster8__q;
    assign oa9 = cluster9__oa;
    assign ob9 = cluster9__ob;
    assign q9 = cluster9__q;
    assign cfg_o = cluster9__cfg_o;

endmodule
