// Automatically generated by PRGA's RTL generator
module cbox_clb_x0y0n (
    output wire [0:0] blkp_clb_x0y0_cin,
    input wire [19:0] cbi_L1_x0y0e,
    input wire [19:0] cbi_L1_x0y0w,
    input wire [3:0] cfg_d
    );
    
    wire [0:0] sw_blkp_clb_x0y0_cin_0__o;
    
    cfg_mux10 sw_blkp_clb_x0y0_cin_0 (
        .i({cbi_L1_x0y0w[16], cbi_L1_x0y0e[16], cbi_L1_x0y0w[12], cbi_L1_x0y0e[12], cbi_L1_x0y0w[8], cbi_L1_x0y0e[8], cbi_L1_x0y0w[4], cbi_L1_x0y0e[4], cbi_L1_x0y0w[0], cbi_L1_x0y0e[0]}),
        .o(sw_blkp_clb_x0y0_cin_0__o),
        .cfg_d(cfg_d)
        );
    
    assign blkp_clb_x0y0_cin = sw_blkp_clb_x0y0_cin_0__o;

endmodule
