// Automatically generated by PRGA's RTL generator
module cfg_mux2 (
    input wire [1:0] i,
    output reg [0:0] o,
    input wire [0:0] cfg_d
    );

    always @* begin
        o = 1'b0;
        case (cfg_d)    // synopsys infer_mux
            1'd0: o = i[0];
            1'd1: o = i[1];
        endcase
    end

endmodule
