// Automatically generated by PRGA's RTL generator
module iob (
    input wire [0:0] exti,
    output wire [0:0] exto,
    output wire [0:0] extoe,
    input wire [0:0] clk,
    input wire [0:0] outpad,
    output wire [0:0] inpad,
    input wire [2:0] cfg_d
    );
    
    wire [0:0] iff__Q;
    wire [0:0] off__Q;
    wire [0:0] sw_inpad_0__o;
    wire [0:0] sw_io_outpad_0__o;
    
    flipflop iff (
        .clk(clk),
        .D(exti),
        .Q(iff__Q)
        );
    flipflop off (
        .clk(clk),
        .D(outpad),
        .Q(off__Q)
        );
    cfg_mux2 sw_inpad_0 (
        .i({exti, iff__Q}),
        .o(sw_inpad_0__o),
        .cfg_d(cfg_d[1])
        );
    cfg_mux2 sw_io_outpad_0 (
        .i({outpad, off__Q}),
        .o(sw_io_outpad_0__o),
        .cfg_d(cfg_d[2])
        );
    
    assign exto = sw_io_outpad_0__o;
    assign extoe = cfg_d[0];
    assign inpad = sw_inpad_0__o;

endmodule
