// Automatically generated by PRGA's RTL generator
module top_sbox_nw (
    output wire [19:0] sgmt_L1_x0y1n,
    input wire [19:0] sbir_L1_x0y1s,
    output wire [19:0] sgmt_L1_x0y0w,
    input wire [19:0] sbir_L1_x0y0e,
    input wire [19:0] sbic_L1_x0y0w,
    input wire [19:0] sbic_L1_x0y1n,
    input wire [19:0] sbid_L1_x0y0w,
    input wire [19:0] sbic_L1_x1y0e,
    output wire [19:0] sgmt_L1_x1y0e,
    input wire [19:0] sbid_L1_x0y1n,
    input wire [79:0] cfg_d
    );
    
    wire [0:0] sw_sgmt_L1_x0y1n_0__o;
    wire [0:0] sw_sgmt_L1_x0y1n_1__o;
    wire [0:0] sw_sgmt_L1_x0y1n_2__o;
    wire [0:0] sw_sgmt_L1_x0y1n_3__o;
    wire [0:0] sw_sgmt_L1_x0y1n_4__o;
    wire [0:0] sw_sgmt_L1_x0y1n_5__o;
    wire [0:0] sw_sgmt_L1_x0y1n_6__o;
    wire [0:0] sw_sgmt_L1_x0y1n_7__o;
    wire [0:0] sw_sgmt_L1_x0y1n_8__o;
    wire [0:0] sw_sgmt_L1_x0y1n_9__o;
    wire [0:0] sw_sgmt_L1_x0y1n_10__o;
    wire [0:0] sw_sgmt_L1_x0y1n_11__o;
    wire [0:0] sw_sgmt_L1_x0y1n_12__o;
    wire [0:0] sw_sgmt_L1_x0y1n_13__o;
    wire [0:0] sw_sgmt_L1_x0y1n_14__o;
    wire [0:0] sw_sgmt_L1_x0y1n_15__o;
    wire [0:0] sw_sgmt_L1_x0y1n_16__o;
    wire [0:0] sw_sgmt_L1_x0y1n_17__o;
    wire [0:0] sw_sgmt_L1_x0y1n_18__o;
    wire [0:0] sw_sgmt_L1_x0y1n_19__o;
    wire [0:0] sw_sgmt_L1_x0y0w_0__o;
    wire [0:0] sw_sgmt_L1_x0y0w_1__o;
    wire [0:0] sw_sgmt_L1_x0y0w_2__o;
    wire [0:0] sw_sgmt_L1_x0y0w_3__o;
    wire [0:0] sw_sgmt_L1_x0y0w_4__o;
    wire [0:0] sw_sgmt_L1_x0y0w_5__o;
    wire [0:0] sw_sgmt_L1_x0y0w_6__o;
    wire [0:0] sw_sgmt_L1_x0y0w_7__o;
    wire [0:0] sw_sgmt_L1_x0y0w_8__o;
    wire [0:0] sw_sgmt_L1_x0y0w_9__o;
    wire [0:0] sw_sgmt_L1_x0y0w_10__o;
    wire [0:0] sw_sgmt_L1_x0y0w_11__o;
    wire [0:0] sw_sgmt_L1_x0y0w_12__o;
    wire [0:0] sw_sgmt_L1_x0y0w_13__o;
    wire [0:0] sw_sgmt_L1_x0y0w_14__o;
    wire [0:0] sw_sgmt_L1_x0y0w_15__o;
    wire [0:0] sw_sgmt_L1_x0y0w_16__o;
    wire [0:0] sw_sgmt_L1_x0y0w_17__o;
    wire [0:0] sw_sgmt_L1_x0y0w_18__o;
    wire [0:0] sw_sgmt_L1_x0y0w_19__o;
    
    cfg_mux3 sw_sgmt_L1_x0y1n_0 (
        .i({sbid_L1_x0y1n[0], sbic_L1_x0y1n[0], sbir_L1_x0y0e[19]}),
        .o(sw_sgmt_L1_x0y1n_0__o),
        .cfg_d(cfg_d[1:0])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_1 (
        .i({sbid_L1_x0y1n[1], sbic_L1_x0y1n[1], sbir_L1_x0y0e[0]}),
        .o(sw_sgmt_L1_x0y1n_1__o),
        .cfg_d(cfg_d[3:2])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_2 (
        .i({sbid_L1_x0y1n[2], sbic_L1_x0y1n[2], sbir_L1_x0y0e[1]}),
        .o(sw_sgmt_L1_x0y1n_2__o),
        .cfg_d(cfg_d[5:4])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_3 (
        .i({sbid_L1_x0y1n[3], sbic_L1_x0y1n[3], sbir_L1_x0y0e[2]}),
        .o(sw_sgmt_L1_x0y1n_3__o),
        .cfg_d(cfg_d[7:6])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_4 (
        .i({sbid_L1_x0y1n[4], sbic_L1_x0y1n[4], sbir_L1_x0y0e[3]}),
        .o(sw_sgmt_L1_x0y1n_4__o),
        .cfg_d(cfg_d[9:8])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_5 (
        .i({sbid_L1_x0y1n[5], sbic_L1_x0y1n[5], sbir_L1_x0y0e[4]}),
        .o(sw_sgmt_L1_x0y1n_5__o),
        .cfg_d(cfg_d[11:10])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_6 (
        .i({sbid_L1_x0y1n[6], sbic_L1_x0y1n[6], sbir_L1_x0y0e[5]}),
        .o(sw_sgmt_L1_x0y1n_6__o),
        .cfg_d(cfg_d[13:12])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_7 (
        .i({sbid_L1_x0y1n[7], sbic_L1_x0y1n[7], sbir_L1_x0y0e[6]}),
        .o(sw_sgmt_L1_x0y1n_7__o),
        .cfg_d(cfg_d[15:14])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_8 (
        .i({sbid_L1_x0y1n[8], sbic_L1_x0y1n[8], sbir_L1_x0y0e[7]}),
        .o(sw_sgmt_L1_x0y1n_8__o),
        .cfg_d(cfg_d[17:16])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_9 (
        .i({sbid_L1_x0y1n[9], sbic_L1_x0y1n[9], sbir_L1_x0y0e[8]}),
        .o(sw_sgmt_L1_x0y1n_9__o),
        .cfg_d(cfg_d[19:18])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_10 (
        .i({sbid_L1_x0y1n[10], sbic_L1_x0y1n[10], sbir_L1_x0y0e[9]}),
        .o(sw_sgmt_L1_x0y1n_10__o),
        .cfg_d(cfg_d[21:20])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_11 (
        .i({sbid_L1_x0y1n[11], sbic_L1_x0y1n[11], sbir_L1_x0y0e[10]}),
        .o(sw_sgmt_L1_x0y1n_11__o),
        .cfg_d(cfg_d[23:22])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_12 (
        .i({sbid_L1_x0y1n[12], sbic_L1_x0y1n[12], sbir_L1_x0y0e[11]}),
        .o(sw_sgmt_L1_x0y1n_12__o),
        .cfg_d(cfg_d[25:24])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_13 (
        .i({sbid_L1_x0y1n[13], sbic_L1_x0y1n[13], sbir_L1_x0y0e[12]}),
        .o(sw_sgmt_L1_x0y1n_13__o),
        .cfg_d(cfg_d[27:26])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_14 (
        .i({sbid_L1_x0y1n[14], sbic_L1_x0y1n[14], sbir_L1_x0y0e[13]}),
        .o(sw_sgmt_L1_x0y1n_14__o),
        .cfg_d(cfg_d[29:28])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_15 (
        .i({sbid_L1_x0y1n[15], sbic_L1_x0y1n[15], sbir_L1_x0y0e[14]}),
        .o(sw_sgmt_L1_x0y1n_15__o),
        .cfg_d(cfg_d[31:30])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_16 (
        .i({sbid_L1_x0y1n[16], sbic_L1_x0y1n[16], sbir_L1_x0y0e[15]}),
        .o(sw_sgmt_L1_x0y1n_16__o),
        .cfg_d(cfg_d[33:32])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_17 (
        .i({sbid_L1_x0y1n[17], sbic_L1_x0y1n[17], sbir_L1_x0y0e[16]}),
        .o(sw_sgmt_L1_x0y1n_17__o),
        .cfg_d(cfg_d[35:34])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_18 (
        .i({sbid_L1_x0y1n[18], sbic_L1_x0y1n[18], sbir_L1_x0y0e[17]}),
        .o(sw_sgmt_L1_x0y1n_18__o),
        .cfg_d(cfg_d[37:36])
        );
    cfg_mux3 sw_sgmt_L1_x0y1n_19 (
        .i({sbid_L1_x0y1n[19], sbic_L1_x0y1n[19], sbir_L1_x0y0e[18]}),
        .o(sw_sgmt_L1_x0y1n_19__o),
        .cfg_d(cfg_d[39:38])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_0 (
        .i({sbid_L1_x0y0w[0], sbic_L1_x0y0w[0], sbir_L1_x0y1s[19]}),
        .o(sw_sgmt_L1_x0y0w_0__o),
        .cfg_d(cfg_d[41:40])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_1 (
        .i({sbid_L1_x0y0w[1], sbic_L1_x0y0w[1], sbir_L1_x0y1s[0]}),
        .o(sw_sgmt_L1_x0y0w_1__o),
        .cfg_d(cfg_d[43:42])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_2 (
        .i({sbid_L1_x0y0w[2], sbic_L1_x0y0w[2], sbir_L1_x0y1s[1]}),
        .o(sw_sgmt_L1_x0y0w_2__o),
        .cfg_d(cfg_d[45:44])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_3 (
        .i({sbid_L1_x0y0w[3], sbic_L1_x0y0w[3], sbir_L1_x0y1s[2]}),
        .o(sw_sgmt_L1_x0y0w_3__o),
        .cfg_d(cfg_d[47:46])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_4 (
        .i({sbid_L1_x0y0w[4], sbic_L1_x0y0w[4], sbir_L1_x0y1s[3]}),
        .o(sw_sgmt_L1_x0y0w_4__o),
        .cfg_d(cfg_d[49:48])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_5 (
        .i({sbid_L1_x0y0w[5], sbic_L1_x0y0w[5], sbir_L1_x0y1s[4]}),
        .o(sw_sgmt_L1_x0y0w_5__o),
        .cfg_d(cfg_d[51:50])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_6 (
        .i({sbid_L1_x0y0w[6], sbic_L1_x0y0w[6], sbir_L1_x0y1s[5]}),
        .o(sw_sgmt_L1_x0y0w_6__o),
        .cfg_d(cfg_d[53:52])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_7 (
        .i({sbid_L1_x0y0w[7], sbic_L1_x0y0w[7], sbir_L1_x0y1s[6]}),
        .o(sw_sgmt_L1_x0y0w_7__o),
        .cfg_d(cfg_d[55:54])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_8 (
        .i({sbid_L1_x0y0w[8], sbic_L1_x0y0w[8], sbir_L1_x0y1s[7]}),
        .o(sw_sgmt_L1_x0y0w_8__o),
        .cfg_d(cfg_d[57:56])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_9 (
        .i({sbid_L1_x0y0w[9], sbic_L1_x0y0w[9], sbir_L1_x0y1s[8]}),
        .o(sw_sgmt_L1_x0y0w_9__o),
        .cfg_d(cfg_d[59:58])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_10 (
        .i({sbid_L1_x0y0w[10], sbic_L1_x0y0w[10], sbir_L1_x0y1s[9]}),
        .o(sw_sgmt_L1_x0y0w_10__o),
        .cfg_d(cfg_d[61:60])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_11 (
        .i({sbid_L1_x0y0w[11], sbic_L1_x0y0w[11], sbir_L1_x0y1s[10]}),
        .o(sw_sgmt_L1_x0y0w_11__o),
        .cfg_d(cfg_d[63:62])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_12 (
        .i({sbid_L1_x0y0w[12], sbic_L1_x0y0w[12], sbir_L1_x0y1s[11]}),
        .o(sw_sgmt_L1_x0y0w_12__o),
        .cfg_d(cfg_d[65:64])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_13 (
        .i({sbid_L1_x0y0w[13], sbic_L1_x0y0w[13], sbir_L1_x0y1s[12]}),
        .o(sw_sgmt_L1_x0y0w_13__o),
        .cfg_d(cfg_d[67:66])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_14 (
        .i({sbid_L1_x0y0w[14], sbic_L1_x0y0w[14], sbir_L1_x0y1s[13]}),
        .o(sw_sgmt_L1_x0y0w_14__o),
        .cfg_d(cfg_d[69:68])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_15 (
        .i({sbid_L1_x0y0w[15], sbic_L1_x0y0w[15], sbir_L1_x0y1s[14]}),
        .o(sw_sgmt_L1_x0y0w_15__o),
        .cfg_d(cfg_d[71:70])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_16 (
        .i({sbid_L1_x0y0w[16], sbic_L1_x0y0w[16], sbir_L1_x0y1s[15]}),
        .o(sw_sgmt_L1_x0y0w_16__o),
        .cfg_d(cfg_d[73:72])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_17 (
        .i({sbid_L1_x0y0w[17], sbic_L1_x0y0w[17], sbir_L1_x0y1s[16]}),
        .o(sw_sgmt_L1_x0y0w_17__o),
        .cfg_d(cfg_d[75:74])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_18 (
        .i({sbid_L1_x0y0w[18], sbic_L1_x0y0w[18], sbir_L1_x0y1s[17]}),
        .o(sw_sgmt_L1_x0y0w_18__o),
        .cfg_d(cfg_d[77:76])
        );
    cfg_mux3 sw_sgmt_L1_x0y0w_19 (
        .i({sbid_L1_x0y0w[19], sbic_L1_x0y0w[19], sbir_L1_x0y1s[18]}),
        .o(sw_sgmt_L1_x0y0w_19__o),
        .cfg_d(cfg_d[79:78])
        );
    
    assign sgmt_L1_x0y1n = {sw_sgmt_L1_x0y1n_19__o, sw_sgmt_L1_x0y1n_18__o, sw_sgmt_L1_x0y1n_17__o, sw_sgmt_L1_x0y1n_16__o, sw_sgmt_L1_x0y1n_15__o, sw_sgmt_L1_x0y1n_14__o, sw_sgmt_L1_x0y1n_13__o, sw_sgmt_L1_x0y1n_12__o, sw_sgmt_L1_x0y1n_11__o, sw_sgmt_L1_x0y1n_10__o, sw_sgmt_L1_x0y1n_9__o, sw_sgmt_L1_x0y1n_8__o, sw_sgmt_L1_x0y1n_7__o, sw_sgmt_L1_x0y1n_6__o, sw_sgmt_L1_x0y1n_5__o, sw_sgmt_L1_x0y1n_4__o, sw_sgmt_L1_x0y1n_3__o, sw_sgmt_L1_x0y1n_2__o, sw_sgmt_L1_x0y1n_1__o, sw_sgmt_L1_x0y1n_0__o};
    assign sgmt_L1_x0y0w = {sw_sgmt_L1_x0y0w_19__o, sw_sgmt_L1_x0y0w_18__o, sw_sgmt_L1_x0y0w_17__o, sw_sgmt_L1_x0y0w_16__o, sw_sgmt_L1_x0y0w_15__o, sw_sgmt_L1_x0y0w_14__o, sw_sgmt_L1_x0y0w_13__o, sw_sgmt_L1_x0y0w_12__o, sw_sgmt_L1_x0y0w_11__o, sw_sgmt_L1_x0y0w_10__o, sw_sgmt_L1_x0y0w_9__o, sw_sgmt_L1_x0y0w_8__o, sw_sgmt_L1_x0y0w_7__o, sw_sgmt_L1_x0y0w_6__o, sw_sgmt_L1_x0y0w_5__o, sw_sgmt_L1_x0y0w_4__o, sw_sgmt_L1_x0y0w_3__o, sw_sgmt_L1_x0y0w_2__o, sw_sgmt_L1_x0y0w_1__o, sw_sgmt_L1_x0y0w_0__o};
    assign sgmt_L1_x1y0e = sbic_L1_x1y0e;

endmodule
