// Automatically generated by PRGA's RTL generator
module cbox_clb_x0y0s (
    output wire [0:0] blkp_clb_x0y0_ce,
    input wire [19:0] cbi_L1_x0v1e,
    input wire [19:0] cbi_L1_x0v1w,
    output wire [0:0] blkp_clb_x0y0_sr,
    input wire [0:0] blkp_clb_x0y0_cout,
    output wire [19:0] cbo_L1_x0v1e,
    output wire [19:0] cbo_L1_x0v1w,
    input wire [7:0] cfg_d
    );
    
    wire [0:0] sw_blkp_clb_x0y0_ce_0__o;
    wire [0:0] sw_blkp_clb_x0y0_sr_0__o;
    
    cfg_mux10 sw_blkp_clb_x0y0_ce_0 (
        .i({cbi_L1_x0v1w[16], cbi_L1_x0v1e[16], cbi_L1_x0v1w[12], cbi_L1_x0v1e[12], cbi_L1_x0v1w[8], cbi_L1_x0v1e[8], cbi_L1_x0v1w[4], cbi_L1_x0v1e[4], cbi_L1_x0v1w[0], cbi_L1_x0v1e[0]}),
        .o(sw_blkp_clb_x0y0_ce_0__o),
        .cfg_d(cfg_d[3:0])
        );
    cfg_mux10 sw_blkp_clb_x0y0_sr_0 (
        .i({cbi_L1_x0v1w[17], cbi_L1_x0v1e[17], cbi_L1_x0v1w[13], cbi_L1_x0v1e[13], cbi_L1_x0v1w[9], cbi_L1_x0v1e[9], cbi_L1_x0v1w[5], cbi_L1_x0v1e[5], cbi_L1_x0v1w[1], cbi_L1_x0v1e[1]}),
        .o(sw_blkp_clb_x0y0_sr_0__o),
        .cfg_d(cfg_d[7:4])
        );
    
    assign blkp_clb_x0y0_ce = sw_blkp_clb_x0y0_ce_0__o;
    assign blkp_clb_x0y0_sr = sw_blkp_clb_x0y0_sr_0__o;
    assign cbo_L1_x0v1e = {9'bx, blkp_clb_x0y0_cout, 9'bx, blkp_clb_x0y0_cout};
    assign cbo_L1_x0v1w = {9'bx, blkp_clb_x0y0_cout, 9'bx, blkp_clb_x0y0_cout};

endmodule
