jobs.build.tasks: [{tool: Make}]
jobs.build.description: "Builds a makefile for running toolbox jobs"

jobs.fpga.tasks: [{tool: FPGAGenTool}]
jobs.fpga.description: "Builds a very simple FPGA for evaluation purposes"
