#----------------------------------------------------------
# Setup
#----------------------------------------------------------
abstract.bin: "/tools/cadence/ICADV/ICADV123/tools/dfII/bin/abstract"
abstract.execute: true 
abstract.cds_path: "../cadence-tstech180"
abstract.library_path: "${abstract.cds_path}/libraries/superswitch"
abstract.cell: "MemsDriver"
abstract.cell_bin: "Block"
abstract.pr_cell_class: "block"
abstract.verilog_dummy_files: []
abstract.metal_stack: [
  "METAL1", 
  "METAL2", 
  "METAL3", 
  "METAL4", 
  "METAL5", 
  "METAL6"
]
#abstract.replay_template: "abstract.replay.old"
#----------------------------------------------------------

#----------------------------------------------------------
# Pins step
#----------------------------------------------------------
abstract.pins_power_names: "^(VDD)|(HVDD)$"
abstract.pins_ground_names: "^VSS$"
abstract.pins_text_pins_map: [
  "(METAL1 METAL1)",
  "(METAL2 METAL2)",
  "(METAL3 METAL3)",
  "(METAL4 METAL4)",
  "(METAL5 METAL5)",
  "(METAL6 METAL6)"
]
abstract.pins_text_promote_level: 0
abstract.pins_boundary_layers: "(prBoundary drawing)"
#----------------------------------------------------------

#----------------------------------------------------------
# Extract step
#----------------------------------------------------------
abstract.extract_connectivity_layers: [
  "(METAL1 METAL1)", 
  "(METAL2 METAL2)"
]
abstract.extract_layers_sig: [
  "(METAL1 METAL1)", 
  "(METAL2 METAL2)"
]
abstract.extract_pin_layers_sig: [
  "METAL1", 
  "METAL2"
]
abstract.extract_num_levels_sig: 32 
abstract.extract_layers_pwr: [
  "(METAL1 METAL1)", 
  "(METAL2 METAL2)"
]
abstract.extract_pin_layers_pwr: [
  "METAL1", 
  "METAL2"
]
abstract.extract_num_levels_pwr: 32 
#----------------------------------------------------------

#----------------------------------------------------------
# Abstract step
#----------------------------------------------------------
abstract.abstract_pin_fracture: true
abstract.abstract_blockage_fracture: true
abstract.abstract_blockage_table: "${abstract.metal_stack}"
abstract.abstract_blockage_detailed_layers: "${abstract.metal_stack}"
abstract.abstract_blockage_cover_layers: []
abstract.abstract_blockage_cover_layers_dist: []
abstract.abstract_adjust_boundary_pins_pwr: true
#----------------------------------------------------------
