liberate.bin: "/tools/cadence/LIBERATE/LIBERATE181/bin/liberate"
liberate.execute: true 

liberate.lib_name: "nem_sw_0p7v_25c_typical" 
liberate.time_unit: "1ps"
liberate.cap_unit: "1ff"

liberate.spice_files: ["lars_erik/nem_sw.spi"]
liberate.voltage: 0.7
liberate.temperature: 25
liberate.input_slew: [5, 10, 20, 40, 80, 160, 320]
liberate.output_load: [0.72, 1.44, 2.88, 5.76, 11.52, 23.04, 46.08]

liberate.cell: "nem_sw"
liberate.cell_pins.input: ["D", "G", "B"]
liberate.cell_pins.output: ["S"]

liberate.arcs:
  - {pin: "S", pin_dir: "R", related_pin: "D", related_pin_dir: "R"}
  - {pin: "S", pin_dir: "F", related_pin: "D", related_pin_dir: "F"}
