// Automatically generated by PRGA's RTL generator
module cfg_mux10 (
    input wire [9:0] i,
    output reg [0:0] o,
    input wire [3:0] cfg_d
    );

    always @* begin
        o = 1'b0;
        case (cfg_d)    // synopsys infer_mux
            4'd0: o = i[0];
            4'd1: o = i[1];
            4'd2: o = i[2];
            4'd3: o = i[3];
            4'd4: o = i[4];
            4'd5: o = i[5];
            4'd6: o = i[6];
            4'd7: o = i[7];
            4'd8: o = i[8];
            4'd9: o = i[9];
        endcase
    end

endmodule
